"""
Remedies and treatment database for all 54 crop diseases.
"""

REMEDIES = {
    # ── BANANA ──────────────────────────────────────────────────────────────
    "BANANA_cordana": {
        "display_name": "Banana Cordana Leaf Spot",
        "severity": "medium",
        "description": "Fungal disease causing brown oval spots with yellow halos on banana leaves.",
        "symptoms": ["Brown/grey oval spots", "Yellow halos around spots", "Premature leaf death"],
        "treatment": [
            "Remove and destroy infected leaves immediately.",
            "Apply Mancozeb (2g/L) or Carbendazim (1g/L) fungicide spray.",
            "Improve field drainage to reduce moisture.",
            "Avoid overhead irrigation.",
        ],
        "prevention": "Maintain proper spacing between plants for airflow. Avoid waterlogging.",
    },
    "BANANA_healthy": {
        "display_name": "Banana – Healthy",
        "severity": "none",
        "description": "Your banana crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Continue regular monitoring, balanced fertilization, and proper irrigation.",
    },
    "BANANA_pestalotiopsis": {
        "display_name": "Banana Pestalotiopsis",
        "severity": "high",
        "description": "Fungal infection causing large necrotic patches on leaves and fruit.",
        "symptoms": ["Large brown necrotic patches", "Grey centers with dark borders", "Fruit rot"],
        "treatment": [
            "Remove and burn infected plant parts.",
            "Apply Copper Oxychloride (3g/L) spray.",
            "Use Trichoderma-based bio-fungicide as soil drench.",
            "Avoid wounding plants during field operations.",
        ],
        "prevention": "Use disease-free planting material. Sterilize tools between plants.",
    },
    "BANANA_sigatoka": {
        "display_name": "Banana Sigatoka (Black Leaf Streak)",
        "severity": "high",
        "description": "One of the most destructive banana diseases worldwide, causing severe yield loss.",
        "symptoms": ["Pale yellow streaks on leaves", "Dark brown/black streaks", "Premature leaf death"],
        "treatment": [
            "Apply Propiconazole or Tridemorph fungicide every 3 weeks.",
            "Remove severely infected leaves (denavelling).",
            "Apply mineral oil + fungicide mixture for systemic control.",
            "Ensure adequate potassium fertilization.",
        ],
        "prevention": "Plant resistant varieties. Regular monitoring every 2 weeks.",
    },

    # ── CHILLI ──────────────────────────────────────────────────────────────
    "Chilli __Whitefly": {
        "display_name": "Chilli Whitefly Infestation",
        "severity": "high",
        "description": "Whitefly infestation that sucks sap and transmits viral diseases.",
        "symptoms": ["Tiny white insects under leaves", "Yellowing leaves", "Honeydew secretion", "Sooty mould"],
        "treatment": [
            "Spray Imidacloprid (0.5ml/L) or Thiamethoxam (0.3g/L).",
            "Use yellow sticky traps to monitor and reduce populations.",
            "Apply Neem oil (5ml/L) as eco-friendly alternative.",
            "Remove heavily infested leaves.",
        ],
        "prevention": "Install insect-proof nets. Avoid excessive nitrogen fertilizer.",
    },
    "Chilli __Yellowish": {
        "display_name": "Chilli Yellowing",
        "severity": "medium",
        "description": "Yellowing of chilli leaves due to nutrient deficiency or disease stress.",
        "symptoms": ["Pale yellow leaves", "Stunted growth", "Interveinal chlorosis"],
        "treatment": [
            "Apply balanced NPK fertilizer (19:19:19) via foliar spray.",
            "Check soil pH — maintain between 6.0–6.8.",
            "Apply Magnesium Sulphate (5g/L) for Mg deficiency.",
            "Rule out viral infection with diagnostic test.",
        ],
        "prevention": "Soil testing before planting. Regular balanced fertilization program.",
    },
    "Chilli__Anthracnos": {
        "display_name": "Chilli Anthracnose",
        "severity": "high",
        "description": "Fungal disease causing fruit rot and significant post-harvest losses.",
        "symptoms": ["Sunken dark lesions on fruit", "Circular brown spots", "Pink/orange spore masses"],
        "treatment": [
            "Spray Carbendazim (1g/L) or Azoxystrobin (1ml/L).",
            "Apply Copper Hydroxide (3g/L) as protective spray.",
            "Harvest fruits at proper maturity stage.",
            "Remove and destroy infected fruits.",
        ],
        "prevention": "Use certified disease-free seeds. Avoid field wounding. Proper post-harvest handling.",
    },
    "Chilli__Damping_Off": {
        "display_name": "Chilli Damping Off",
        "severity": "high",
        "description": "Soilborne fungal disease killing seedlings at or near soil level.",
        "symptoms": ["Seedlings falling over", "Water-soaked stem at soil level", "Mass seedling death"],
        "treatment": [
            "Drench soil with Metalaxyl + Mancozeb (2g/L).",
            "Apply Trichoderma viride (5g/L) as biological control.",
            "Remove dead seedlings immediately to prevent spread.",
            "Reduce irrigation frequency — avoid overwatering.",
        ],
        "prevention": "Use sterilized nursery soil. Treat seeds with Thiram before sowing.",
    },
    "Chilli__Leaf_Curl_Virus": {
        "display_name": "Chilli Leaf Curl Virus",
        "severity": "critical",
        "description": "Viral disease transmitted by whiteflies causing severe stunting and yield loss.",
        "symptoms": ["Upward leaf curling", "Stunted plants", "Distorted fruits", "Yellowing"],
        "treatment": [
            "Remove and destroy infected plants immediately — no cure exists.",
            "Control whitefly vector with Imidacloprid (0.5ml/L).",
            "Apply mineral oil spray to reduce virus spread.",
            "Install yellow sticky traps.",
        ],
        "prevention": "Plant resistant varieties. Use virus-free seedlings. Control whiteflies from day one.",
    },
    "Chilli__Leaf_Spot": {
        "display_name": "Chilli Leaf Spot",
        "severity": "medium",
        "description": "Fungal/bacterial disease causing spots leading to defoliation.",
        "symptoms": ["Circular brown spots", "Yellow halos", "Premature leaf drop"],
        "treatment": [
            "Spray Mancozeb (2.5g/L) or Copper Oxychloride (3g/L).",
            "Apply Azoxystrobin (1ml/L) for better systemic control.",
            "Remove infected leaves before spraying.",
        ],
        "prevention": "Avoid overhead irrigation. Maintain proper plant spacing.",
    },
    "Chilli__Veinal_Mottle_Virus": {
        "display_name": "Chilli Veinal Mottle Virus",
        "severity": "critical",
        "description": "Viral disease causing mosaic patterns and severe yield reduction.",
        "symptoms": ["Green/yellow mosaic patterns", "Vein clearing", "Distorted leaves", "Stunting"],
        "treatment": [
            "No cure — remove and destroy infected plants.",
            "Control aphid vectors with Dimethoate (2ml/L).",
            "Apply reflective mulches to deter aphids.",
        ],
        "prevention": "Use certified virus-free seed. Control insect vectors aggressively.",
    },
    "Chilli___healthy": {
        "display_name": "Chilli – Healthy",
        "severity": "none",
        "description": "Your chilli crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Continue regular monitoring and balanced fertilizer application.",
    },

    # ── CORN (MAIZE) ─────────────────────────────────────────────────────────
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": {
        "display_name": "Maize Gray Leaf Spot",
        "severity": "high",
        "description": "Fungal disease causing rectangular gray lesions parallel to leaf veins.",
        "symptoms": ["Long rectangular gray/tan lesions", "Lesions bound by leaf veins", "Premature drying"],
        "treatment": [
            "Apply Azoxystrobin + Propiconazole (1ml/L) fungicide.",
            "Apply Tebuconazole (1ml/L) at early disease stage.",
            "Remove severely infected lower leaves.",
        ],
        "prevention": "Plant resistant hybrids. Rotate crops — avoid continuous maize cultivation.",
    },
    "Corn_(maize)___Common_rust_": {
        "display_name": "Maize Common Rust",
        "severity": "medium",
        "description": "Fungal disease causing brick-red pustules on both sides of leaves.",
        "symptoms": ["Brick-red powdery pustules", "Pustules on both leaf surfaces", "Yellowing around pustules"],
        "treatment": [
            "Apply Mancozeb (2.5g/L) + Propiconazole (1ml/L).",
            "Spray Trifloxystrobin (0.5g/L) for systemic control.",
            "Apply at early tasseling stage for best results.",
        ],
        "prevention": "Plant rust-resistant varieties. Early planting to avoid peak rust season.",
    },
    "Corn_(maize)___Northern_Leaf_Blight": {
        "display_name": "Maize Northern Leaf Blight",
        "severity": "high",
        "description": "Fungal disease causing large cigar-shaped tan lesions on leaves.",
        "symptoms": ["Large cigar-shaped tan/grey lesions", "Lesions 5–15cm long", "Premature drying"],
        "treatment": [
            "Spray Propiconazole (1ml/L) at early stage.",
            "Apply Azoxystrobin + Propiconazole (1ml/L) tank mix.",
            "Use fungicide at silking stage for maximum protection.",
        ],
        "prevention": "Use resistant hybrids. Crop rotation with non-host crops.",
    },
    "Corn_(maize)___healthy": {
        "display_name": "Maize – Healthy",
        "severity": "none",
        "description": "Your maize crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Maintain balanced NPK fertilization and timely irrigation.",
    },

    # ── MANGO ────────────────────────────────────────────────────────────────
    "MANGO_Anthracnose": {
        "display_name": "Mango Anthracnose",
        "severity": "high",
        "description": "Most common mango disease causing fruit rot and significant post-harvest losses.",
        "symptoms": ["Black sunken spots on fruit", "Brown leaf spots", "Blossom blight", "Fruit mummification"],
        "treatment": [
            "Spray Carbendazim (1g/L) or Thiophanate-methyl (1g/L).",
            "Apply Copper Oxychloride (3g/L) as protective spray before rains.",
            "Post-harvest hot water treatment (52°C for 5 minutes).",
            "Remove and destroy mummified fruits.",
        ],
        "prevention": "Prune trees for better airflow. Copper spray before flowering.",
    },
    "MANGO_Bacterial Canker": {
        "display_name": "Mango Bacterial Canker",
        "severity": "high",
        "description": "Bacterial disease causing cankers on stems, leaves, and fruits.",
        "symptoms": ["Water-soaked lesions on leaves", "Cankers on branches", "Fruit cracking", "Gum exudation"],
        "treatment": [
            "Remove and destroy infected branches by cutting 30cm below lesion.",
            "Apply Copper Hydroxide (3g/L) or Bordeaux mixture.",
            "Spray Streptomycin + Copper Oxychloride mixture.",
            "Disinfect all pruning tools with 10% bleach solution.",
        ],
        "prevention": "Avoid wounding trees. No overhead irrigation. Use certified planting material.",
    },
    "MANGO_Cutting Weevil": {
        "display_name": "Mango Cutting Weevil",
        "severity": "medium",
        "description": "Weevil pest cutting shoots and causing them to droop.",
        "symptoms": ["Drooping shoot tips", "Circular cuts on tender shoots", "Wilting new growth"],
        "treatment": [
            "Spray Chlorpyrifos (2ml/L) or Quinalphos (2ml/L).",
            "Collect and destroy fallen shoots.",
            "Apply sticky bands on tree trunks to prevent weevil climbing.",
        ],
        "prevention": "Regular monitoring during new flush emergence. Remove alternative host plants.",
    },
    "MANGO_Die Back": {
        "display_name": "Mango Die Back",
        "severity": "high",
        "description": "Fungal disease causing progressive dying back of shoots from tip to base.",
        "symptoms": ["Tip drying and browning", "Progressive shoot death", "Dark discoloration under bark"],
        "treatment": [
            "Cut off infected branches 10–15cm below visible symptoms.",
            "Paint cut surfaces with Bordeaux paste or Copper Oxychloride.",
            "Spray Carbendazim (1g/L) on entire tree.",
            "Improve tree nutrition — apply zinc and boron micronutrients.",
        ],
        "prevention": "Avoid mechanical injury. Proper pruning with sterilized tools.",
    },
    "MANGO_Gall Midge": {
        "display_name": "Mango Gall Midge",
        "severity": "medium",
        "description": "Midge pest causing abnormal gall formation on leaves and inflorescences.",
        "symptoms": ["Abnormal galls on leaves", "Inflorescence distortion", "Stunted new growth"],
        "treatment": [
            "Spray Dimethoate (2ml/L) or Malathion (2ml/L) at bud burst.",
            "Remove and destroy galled plant parts.",
            "Apply Imidacloprid (0.5ml/L) at early midge emergence.",
        ],
        "prevention": "Destroy leaf litter where midges pupate. Light traps during adult emergence.",
    },
    "MANGO_Healthy": {
        "display_name": "Mango – Healthy",
        "severity": "none",
        "description": "Your mango tree looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Regular pruning after harvest. Balanced fertilizer annually.",
    },
    "MANGO_Powdery Mildew": {
        "display_name": "Mango Powdery Mildew",
        "severity": "high",
        "description": "Fungal disease during flowering causing powdery white growth and flower drop.",
        "symptoms": ["White powdery coating on flowers", "Flower and fruit drop", "Reduced fruit set"],
        "treatment": [
            "Spray Wettable Sulphur (3g/L) at 15-day intervals.",
            "Apply Triadimefon (1g/L) or Hexaconazole (1ml/L).",
            "Spray at bud emergence, full bloom, and after fruit set.",
        ],
        "prevention": "3 sprays: at panicle emergence, full bloom, and after fruit set.",
    },
    "MANGO_Sooty Mould": {
        "display_name": "Mango Sooty Mould",
        "severity": "medium",
        "description": "Fungal growth on honeydew secreted by sap-sucking insects.",
        "symptoms": ["Black sooty coating on leaves/fruit", "Reduced photosynthesis", "Poor fruit quality"],
        "treatment": [
            "Control underlying insect pests (mealybugs, scales) with Imidacloprid.",
            "Wash affected areas with mild soap water spray.",
            "Apply Copper Oxychloride (3g/L) to control mould.",
            "Spray Neem oil (5ml/L) to disrupt pest cycle.",
        ],
        "prevention": "Control sap-sucking insects before mould develops. Sticky trunk bands.",
    },

    # ── PADDY (UPPERCASE) ────────────────────────────────────────────────────
    "PADDY_dead_heart": {
        "display_name": "Paddy Dead Heart (Stem Borer)",
        "severity": "critical",
        "description": "Stem borer larva boring into stems causing dead heart symptom in vegetative stage.",
        "symptoms": ["Central shoot drying (dead heart)", "Easy pull-out of central shoot", "Pinhole entry marks"],
        "treatment": [
            "Apply Carbofuran 3G (25 kg/ha) or Chlorpyrifos granules.",
            "Release Trichogramma egg parasitoid (1 lakh/ha).",
            "Cut and destroy egg masses on leaves.",
            "Apply Cartap Hydrochloride (2g/L) spray.",
        ],
        "prevention": "Trim leaf tips before transplanting. Avoid excessive nitrogen. Light traps for adults.",
    },

    # ── POTATO ───────────────────────────────────────────────────────────────
    "Potato___Early_blight": {
        "display_name": "Potato Early Blight",
        "severity": "medium",
        "description": "Fungal disease causing target-like lesions on lower leaves first.",
        "symptoms": ["Concentric ring 'target' lesions", "Brown/black spots", "Yellowing around spots", "Lower leaf death"],
        "treatment": [
            "Apply Mancozeb (2.5g/L) or Chlorothalonil (2g/L) every 7–10 days.",
            "Add Azoxystrobin (1ml/L) for systemic protection.",
            "Remove and destroy severely infected lower leaves.",
        ],
        "prevention": "Rotate with non-solanaceous crops. Use certified disease-free seed tubers.",
    },
    "Potato___Late_blight": {
        "display_name": "Potato Late Blight",
        "severity": "critical",
        "description": "Most devastating potato disease — can destroy entire crop within days in wet weather.",
        "symptoms": ["Water-soaked dark lesions", "White mould on leaf undersides", "Rapid plant collapse", "Tuber rot"],
        "treatment": [
            "Apply Metalaxyl + Mancozeb (2.5g/L) immediately.",
            "Spray Cymoxanil + Mancozeb (2.5g/L) every 5–7 days.",
            "Remove and destroy infected plants immediately.",
            "Avoid irrigation — dry conditions slow the disease.",
        ],
        "prevention": "Plant resistant varieties. Preventive copper spray before rains. Monitor weather forecasts.",
    },
    "Potato___healthy": {
        "display_name": "Potato – Healthy",
        "severity": "none",
        "description": "Your potato crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Use certified seed tubers. Rotate crops every season.",
    },

    # ── SUGARCANE ────────────────────────────────────────────────────────────
    "SUGARCANE_Healthy leaf": {
        "display_name": "Sugarcane – Healthy",
        "severity": "none",
        "description": "Your sugarcane crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Regular ratoon management and balanced fertilization.",
    },
    "SUGARCANE_Red Rot": {
        "display_name": "Sugarcane Red Rot",
        "severity": "critical",
        "description": "Most serious sugarcane disease causing red discoloration of internal stalk tissue.",
        "symptoms": ["Red internal stalk discoloration", "White patches with red borders", "Sour smell from stalks", "Wilting"],
        "treatment": [
            "Remove and destroy infected stools immediately.",
            "No effective chemical cure — removal is essential.",
            "Drench soil with Carbendazim (0.1%).",
            "Plant resistant varieties in affected fields.",
        ],
        "prevention": "Use disease-free seed cane. Treat setts with Carbendazim before planting. Avoid waterlogging.",
    },
    "SUGARCANE_Wolly Aphid": {
        "display_name": "Sugarcane Woolly Aphid",
        "severity": "high",
        "description": "Invasive pest forming woolly white colonies on leaves causing severe yield loss.",
        "symptoms": ["White woolly masses on leaf undersides", "Honeydew secretion", "Sooty mould", "Stunting"],
        "treatment": [
            "Spray Dimethoate (2ml/L) or Thiamethoxam (0.3g/L).",
            "Apply Neem oil (5ml/L) + soap (3ml/L) mixture.",
            "Release biological control agent Dipha aphidivora.",
            "Destroy crop residues after harvest.",
        ],
        "prevention": "Monitor regularly from June–October. Border row spraying during outbreak.",
    },

    # ── TOMATO ───────────────────────────────────────────────────────────────
    "Tomato___Bacterial_spot": {
        "display_name": "Tomato Bacterial Spot",
        "severity": "high",
        "description": "Bacterial disease causing spots on leaves and fruits reducing market value.",
        "symptoms": ["Small water-soaked leaf spots", "Brown spots with yellow halos", "Scabby fruit lesions"],
        "treatment": [
            "Apply Copper Hydroxide (3g/L) + Mancozeb (2g/L) spray.",
            "Use Streptomycin (500ppm) spray every 7 days.",
            "Remove and destroy infected plant debris.",
        ],
        "prevention": "Use disease-free seeds. Avoid overhead irrigation. Rotate crops.",
    },
    "Tomato___Early_blight": {
        "display_name": "Tomato Early Blight",
        "severity": "medium",
        "description": "Common fungal disease causing target-board lesions and defoliation.",
        "symptoms": ["Concentric ring lesions on older leaves", "Dark brown spots", "Yellowing", "Defoliation"],
        "treatment": [
            "Spray Mancozeb (2.5g/L) or Iprodione (1g/L) every 7–10 days.",
            "Apply Azoxystrobin (1ml/L) for systemic control.",
            "Remove infected leaves from bottom up.",
        ],
        "prevention": "Mulching to prevent soil splash. Stake plants for airflow. Crop rotation.",
    },
    "Tomato___Late_blight": {
        "display_name": "Tomato Late Blight",
        "severity": "critical",
        "description": "Devastating disease that can destroy entire crop rapidly in cool, wet conditions.",
        "symptoms": ["Large water-soaked dark lesions", "White mould on undersides", "Rapid collapse", "Fruit brown rot"],
        "treatment": [
            "Spray Metalaxyl + Mancozeb (2.5g/L) immediately.",
            "Apply Cymoxanil + Mancozeb (2.5g/L) every 5 days.",
            "Remove infected plants from field.",
        ],
        "prevention": "Plant resistant varieties. Preventive spray before monsoon. Avoid overhead irrigation.",
    },
    "Tomato___Leaf_Mold": {
        "display_name": "Tomato Leaf Mold",
        "severity": "medium",
        "description": "Fungal disease common in greenhouse/high-humidity conditions.",
        "symptoms": ["Pale green/yellow spots on upper surface", "Olive-green mold below", "Leaf curl"],
        "treatment": [
            "Apply Mancozeb (2.5g/L) or Chlorothalonil (2g/L).",
            "Improve ventilation in greenhouse.",
            "Reduce humidity by increasing plant spacing.",
        ],
        "prevention": "Maintain relative humidity below 85%. Use resistant varieties.",
    },
    "Tomato___Septoria_leaf_spot": {
        "display_name": "Tomato Septoria Leaf Spot",
        "severity": "medium",
        "description": "Fungal disease causing numerous small spots with white centers.",
        "symptoms": ["Many small circular spots", "White/tan centers with dark borders", "Defoliation from bottom"],
        "treatment": [
            "Apply Mancozeb (2.5g/L) + Chlorothalonil (2g/L).",
            "Spray Azoxystrobin (1ml/L) for systemic control.",
            "Remove infected leaves at first sign.",
        ],
        "prevention": "Use disease-free seed. Mulch to reduce soil splash. Crop rotation.",
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "display_name": "Tomato Spider Mites",
        "severity": "high",
        "description": "Tiny mites causing stippling, bronzing, and webbing on leaves.",
        "symptoms": ["Fine stippling on leaves", "Bronze/silver discoloration", "Fine webbing", "Leaf drop"],
        "treatment": [
            "Apply Abamectin (0.5ml/L) or Bifenazate (1ml/L) miticide.",
            "Spray Neem oil (5ml/L) as organic option.",
            "Increase humidity — mites prefer hot, dry conditions.",
            "Release predatory mite Phytoseiulus persimilis.",
        ],
        "prevention": "Avoid dusty conditions. Avoid excessive nitrogen. Monitor undersides of leaves.",
    },
    "Tomato___Target_Spot": {
        "display_name": "Tomato Target Spot",
        "severity": "medium",
        "description": "Fungal disease causing concentric ring lesions on fruit and leaves.",
        "symptoms": ["Concentric ring lesions", "Brown spots with yellow halos", "Both leaf and fruit affected"],
        "treatment": [
            "Apply Chlorothalonil (2g/L) or Azoxystrobin (1ml/L).",
            "Spray Copper Oxychloride (3g/L) as protective measure.",
        ],
        "prevention": "Good airflow. Staking. Avoid overhead irrigation.",
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "display_name": "Tomato Yellow Leaf Curl Virus (TYLCV)",
        "severity": "critical",
        "description": "Devastating viral disease transmitted by whiteflies — no cure.",
        "symptoms": ["Upward leaf curling", "Severe yellowing", "Stunted plants", "Little to no fruit"],
        "treatment": [
            "Remove and destroy infected plants immediately.",
            "Control whitefly vectors urgently with Imidacloprid (0.5ml/L).",
            "Apply reflective silver mulch to repel whiteflies.",
            "Install yellow sticky traps.",
        ],
        "prevention": "Plant TYLCV-resistant varieties. Screen nurseries. Early whitefly control.",
    },
    "Tomato___Tomato_mosaic_virus": {
        "display_name": "Tomato Mosaic Virus (ToMV)",
        "severity": "critical",
        "description": "Viral disease causing mosaic patterns and severe yield reduction.",
        "symptoms": ["Light/dark green mosaic pattern", "Leaf distortion", "Stunted growth", "Poor fruit set"],
        "treatment": [
            "No cure — remove and destroy infected plants.",
            "Disinfect hands with soap before handling plants.",
            "Disinfect tools with 1% bleach solution.",
        ],
        "prevention": "Use certified virus-free seed. Treat seed with 10% trisodium phosphate. No tobacco handling.",
    },
    "Tomato___healthy": {
        "display_name": "Tomato – Healthy",
        "severity": "none",
        "description": "Your tomato crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Continue regular monitoring. Balanced fertilization. Avoid overwatering.",
    },

    # ── WHEAT ────────────────────────────────────────────────────────────────
    "Wheat___Brown_Rust": {
        "display_name": "Wheat Brown Rust (Leaf Rust)",
        "severity": "high",
        "description": "Most widespread wheat rust disease affecting leaves significantly.",
        "symptoms": ["Small orange-brown pustules on leaves", "Pustules only on upper surface", "Yellow halo around pustules"],
        "treatment": [
            "Apply Propiconazole (1ml/L) or Tebuconazole (1ml/L).",
            "Spray Mancozeb (2.5g/L) as protective measure.",
            "Apply at first sign — early treatment is critical.",
        ],
        "prevention": "Plant resistant varieties. Timely sowing. Avoid late sowing.",
    },
    "Wheat___Healthy": {
        "display_name": "Wheat – Healthy",
        "severity": "none",
        "description": "Your wheat crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Balanced NPK fertilization. Timely irrigation at critical crop stages.",
    },
    "Wheat___Yellow_Rust": {
        "display_name": "Wheat Yellow Rust (Stripe Rust)",
        "severity": "critical",
        "description": "Most damaging wheat rust — can cause 70-100% yield loss if unchecked.",
        "symptoms": ["Yellow-orange pustules in stripes", "Powder on fingers when rubbed", "Cool weather favored"],
        "treatment": [
            "Apply Propiconazole (1ml/L) immediately at first sign.",
            "Spray Tebuconazole + Trifloxystrobin (1ml/L) mixture.",
            "Follow up spray after 14–21 days.",
        ],
        "prevention": "Plant resistant varieties. Avoid late sowing. Monitor closely in cool, cloudy weather.",
    },

    # ── PADDY (lowercase) ────────────────────────────────────────────────────
    "paddy_bacterial_leaf_blight": {
        "display_name": "Paddy Bacterial Leaf Blight",
        "severity": "critical",
        "description": "Most serious bacterial disease of rice causing whitish wilting of leaves.",
        "symptoms": ["Yellowing from leaf tips/margins", "Water-soaked lesions", "Milky/yellow bacterial ooze"],
        "treatment": [
            "Apply Copper Oxychloride (3g/L) + Streptomycin (500ppm).",
            "Drain excess water from field.",
            "Apply Bleaching Powder (10 kg/ha) in irrigation water.",
            "Reduce nitrogen application.",
        ],
        "prevention": "Use resistant varieties. Balanced nitrogen. Drain stagnant water.",
    },
    "paddy_bacterial_leaf_streak": {
        "display_name": "Paddy Bacterial Leaf Streak",
        "severity": "high",
        "description": "Bacterial disease causing narrow water-soaked streaks between leaf veins.",
        "symptoms": ["Narrow brown water-soaked streaks", "Yellow-orange bacterial exudate", "Inter-vein lesions"],
        "treatment": [
            "Spray Copper Hydroxide (3g/L) or Copper Oxychloride.",
            "Apply Streptomycin (500ppm) every 10 days.",
            "Reduce plant density.",
        ],
        "prevention": "Avoid overhead irrigation. Use clean certified seed.",
    },
    "paddy_bacterial_panicle_blight": {
        "display_name": "Paddy Bacterial Panicle Blight",
        "severity": "critical",
        "description": "Bacterial disease causing grain sterility and discoloration of panicles.",
        "symptoms": ["Sterile white grains", "Brown discolored panicles", "Floret failure"],
        "treatment": [
            "No effective chemical control at panicle stage.",
            "Apply Copper spray preventively before heading.",
            "Reduce nitrogen topdressing near heading.",
        ],
        "prevention": "Balanced fertilization. Avoid drought stress at heading stage.",
    },
    "paddy_blast": {
        "display_name": "Paddy Blast (Rice Blast)",
        "severity": "critical",
        "description": "Most destructive rice disease worldwide affecting all parts of the plant.",
        "symptoms": ["Diamond-shaped grey/white lesions", "Neck rot (neck blast)", "White empty panicles"],
        "treatment": [
            "Apply Tricyclazole (0.6g/L) or Isoprothiolane (1.5ml/L).",
            "Spray at early tillering and panicle initiation stages.",
            "Apply Carbendazim (1g/L) as alternative.",
        ],
        "prevention": "Plant resistant varieties. Balanced nitrogen. Avoid excess humidity. Prophylactic spray.",
    },
    "paddy_brown_spot": {
        "display_name": "Paddy Brown Spot",
        "severity": "high",
        "description": "Fungal disease associated with soil nutrient deficiency, especially potassium.",
        "symptoms": ["Oval brown spots on leaves/grains", "White centers with brown borders", "Grain discoloration"],
        "treatment": [
            "Apply Mancozeb (2.5g/L) or Iprodione (1g/L).",
            "Apply Potassium fertilizer (MOP at 60kg/ha).",
            "Spray micronutrient mixture (Zinc, Manganese).",
        ],
        "prevention": "Balanced potassium and silicon nutrition. Treat seed before planting.",
    },
    "paddy_class": {
        "display_name": "Paddy – Class (Unverified)",
        "severity": "unknown",
        "description": "Unable to clearly identify disease. Please consult an agricultural expert.",
        "symptoms": [],
        "treatment": ["Consult your nearest Krishi Vigyan Kendra (KVK) or agricultural expert."],
        "prevention": "Regular field monitoring. Balanced crop nutrition.",
    },
    "paddy_downy_mildew": {
        "display_name": "Paddy Downy Mildew",
        "severity": "medium",
        "description": "Fungal-like disease causing pale green/yellow stripes on leaves.",
        "symptoms": ["Yellow/pale green striped leaves", "Stunted growth", "Twisted malformed leaves"],
        "treatment": [
            "Apply Metalaxyl + Mancozeb (2.5g/L).",
            "Seed treatment with Metalaxyl (3g/kg seed).",
            "Remove and destroy severely affected plants.",
        ],
        "prevention": "Use certified disease-free seed. Seed treatment before planting.",
    },
    "paddy_hispa": {
        "display_name": "Paddy Hispa (Rice Hispa)",
        "severity": "medium",
        "description": "Insect pest that scrapes leaf surfaces causing white streaks.",
        "symptoms": ["White streaks on leaves", "Leaves turning whitish", "Irregular white blotches"],
        "treatment": [
            "Clip the tips of infested leaves and destroy.",
            "Spray Chlorpyrifos (2ml/L) or Quinalphos (2ml/L).",
            "Apply Neem oil (5ml/L) as eco-friendly option.",
        ],
        "prevention": "Avoid excessive nitrogen. Use light traps. Remove grasses from field bunds.",
    },
    "paddy_normal": {
        "display_name": "Paddy – Healthy (Normal)",
        "severity": "none",
        "description": "Your paddy crop looks healthy! No disease detected.",
        "symptoms": [],
        "treatment": ["No treatment needed."],
        "prevention": "Regular field monitoring. Balanced NPK + Zinc fertilization.",
    },
    "paddy_tungro": {
        "display_name": "Paddy Tungro Disease",
        "severity": "critical",
        "description": "Viral disease transmitted by green leafhopper — one of the most serious rice diseases.",
        "symptoms": ["Orange/yellow discoloration", "Stunted plants", "Reduced tillering", "Green leafhopper presence"],
        "treatment": [
            "No cure — remove and destroy infected plants.",
            "Control green leafhopper vector with Imidacloprid (0.5ml/L).",
            "Apply Carbofuran 3G granules in nursery.",
        ],
        "prevention": "Plant resistant varieties (IR 36, IR 64). Synchronize planting. Control leafhoppers.",
    },
}

SEVERITY_COLORS = {
    "none": "#22c55e",
    "medium": "#f59e0b",
    "high": "#f97316",
    "critical": "#ef4444",
    "unknown": "#8b5cf6",
}

def get_remedy(class_name: str) -> dict:
    """Return remedy info for a given class name."""
    return REMEDIES.get(class_name, {
        "display_name": class_name.replace("_", " ").replace("___", " – "),
        "severity": "unknown",
        "description": "Disease information not found. Please consult an agricultural expert.",
        "symptoms": [],
        "treatment": ["Consult your nearest Krishi Vigyan Kendra (KVK) or agricultural expert."],
        "prevention": "Regular field monitoring.",
    })
